"""add password_changed_at to user

Revision ID: 55b15e30462a
Revises: ee7e6753e23b
Create Date: 2026-08-25 20:14:13.829628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated migrations reference sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = '55b15e30462a'
down_revision: Union[str, Sequence[str], None] = 'ee7e6753e23b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_changed_at')
    # ### end Alembic commands ###
