"""add is_superuser to user

Revision ID: ee7e6753e23b
Revises: fd78fd6886c8
Create Date: 2026-08-21 15:40:48.169159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated migrations reference sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = 'ee7e6753e23b'
down_revision: Union[str, Sequence[str], None] = 'fd78fd6886c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default added by hand. Autogenerate produced this column as NOT NULL with
    # no default, which Postgres rejects on a table that already has rows - there is
    # nothing to put in the new column for them. server_default tells Postgres what to
    # backfill existing rows with, and it is a database-level default, unlike the
    # Field(default=False) in the model which only applies to objects Python creates.
    op.add_column(
        'user',
        sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###
